# Generated by Django 4.1.7 on 2023-04-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0002_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
