# Generated by Django 4.1.7 on 2023-04-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0007_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
