# Generated by Django 4.1.7 on 2023-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0008_rename_name_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
